import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";

const SKIP_FILES = new Set(["index.ts", "types.ts"]);

type GuideEntry = {
  filename: string;
  slug: string;
  publishedAt: string;
};

function isGuideFile(filename: string): boolean {
  return (
    filename.endsWith(".ts") &&
    !filename.endsWith(".test.ts") &&
    !SKIP_FILES.has(filename)
  );
}

function slugToIdent(slug: string): string {
  const camel = slug.replace(/-([a-z0-9])/gi, (_, char: string) =>
    char.toUpperCase()
  );
  return `guide_${camel}`;
}

function parseGuideMeta(source: string, filename: string): GuideEntry {
  if (!source.includes("export const guide")) {
    throw new Error(`${filename}: must export \`const guide\``);
  }

  const slugMatch = source.match(/slug:\s*"([^"]+)"/);
  const publishedMatch = source.match(/publishedAt:\s*"([^"]+)"/);
  if (!slugMatch) {
    throw new Error(`${filename}: missing slug`);
  }
  if (!publishedMatch) {
    throw new Error(`${filename}: missing publishedAt`);
  }

  const expectedSlug = basename(filename, ".ts");
  if (slugMatch[1] !== expectedSlug) {
    throw new Error(
      `${filename}: slug "${slugMatch[1]}" must match filename "${expectedSlug}"`
    );
  }

  return { filename, slug: slugMatch[1], publishedAt: publishedMatch[1] };
}

export function generateGuidesIndex(rootDir = process.cwd()): string {
  const dir = join(rootDir, "lib/content/guides");
  const entries = readdirSync(dir)
    .filter(isGuideFile)
    .map((filename) => {
      const source = readFileSync(join(dir, filename), "utf8");
      return parseGuideMeta(source, filename);
    });

  if (entries.length === 0) {
    throw new Error(`No guide files found in ${dir}`);
  }

  entries.sort(
    (a, b) =>
      a.publishedAt.localeCompare(b.publishedAt) || a.slug.localeCompare(b.slug)
  );

  const imports = entries
    .map(
      (entry) =>
        `import { guide as ${slugToIdent(entry.slug)} } from "./${entry.slug}";`
    )
    .join("\n");

  const list = entries
    .map((entry) => `  ${slugToIdent(entry.slug)},`)
    .join("\n");

  const output = `// Auto-generated by scripts/generate-guides-index.ts.
// Do not edit. Add a guide by creating lib/content/guides/<slug>.ts.

import type { Guide } from "./types";
${imports}

export type { Guide };

export const guides: Guide[] = [
${list}
];

export function getGuide(slug: string): Guide | undefined {
  return guides.find((g) => g.slug === slug);
}

export function getAllGuideSlugs(): string[] {
  return guides.map((g) => g.slug);
}
`;

  const outPath = join(dir, "index.ts");
  const previous = existsSync(outPath) ? readFileSync(outPath, "utf8") : "";
  if (previous !== output) {
    writeFileSync(outPath, output);
  }

  return outPath;
}

generateGuidesIndex();
